console.log("5 + \"34\": ", 5 + "34");
console.log(5 - "4");
console.log("10 % 5: ", 10 % 5);
console.log(5 % 10);
console.log("Java" + "Script");
console.log(" " + " ");
console.log(" " + 0);
console.log("true + true: ", true + true);
console.log("true + false: ", true + false);
console.log("false + true: ", false + true);
console.log("false - true: ", false - true);